---

stages:
  - lint
  - test

variables:
  FEATURES: ""
  RUST_BACKTRACE: "full"

.show-version:
  before_script:
    - apt-get update; apt-get install -y --no-install-recommends pkg-config libssl-dev libicu-dev
    - rustc --version
    - cargo --version

.stable:
  image: rust:slim
  extends:
    - .show-version

.nightly:
  image: rustlang/rust:nightly-slim
  # It's not often, but it happens nightly breaks, surprisingly.
  allow_failure: true
  extends:
    - .show-version

.test:
  stage: test
  script:
    - cargo test --verbose --release -- --include-ignored
    - cargo test --verbose --no-default-features
  variables:
    RUSTFLAGS: " -D warnings"

rustfmt:
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt --check
  extends:
    - .stable

stable-test:
  extends:
    - .test
    - .stable

nightly-test:
  extends:
    - .test
    - .nightly
